### ISSUE TITLE
[PE-D][Tester A] example input date format is wrong compared to the date format required

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-4/tp#96] opened 2024-04-05 19:18 UTC
![image.png](https://raw.githubusercontent.com/Greg-Tan/ped/main/files/0cb8c010-e6e6-4e97-8cc3-0a80f3e68d89.png)

This is the example input provided by your command output and it does not match the date format required

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Greg-Tan/ped#7

**Comment by meenulekha** [comment] 2024-04-10 15:50
Duplicate of #101

**Comment by meenulekha** [comment] 2024-04-11 14:41
descriptive title: ✔️
enough details: ✔️
severity/type labels chosen are not too far off: ❌ (severity might be on the lower side)
non-confrontational tone: ✔️
points out a potentially problematic behavior (or a good way to improve the product): ✔️
Not good report

**Closed** 2024-04-13 15:17 UTC
Labels: severity.Low, duplicate, PE-D.NotGood
